### ISSUE TITLE
can't allow edited animals into pens

### ISSUE THREAD

**Issue by inikishev** [XT-0xFF/CustomizeAnimals#1]
if I add roaming interval to any animal that doesn't have it, that animal won't appear in pen animals filter list, so I can't put it into a pen. I have to restart the game for pen animal list to update. Maybe you could force that list to update each time roaming interval is added to an animal?

**Comment by ChrisF-127** [comment]
Good point!
Forced the animal filters for the pen list to reset upon changing an animal to or from being a roamer, thereby updating the pens's animal selection list as the filters are recreated.

Should hopefully work without reloading now.
