### ISSUE TITLE
System.MissingMethodException: bool Verse.Widgets.RadioButton(single,single,bool)

### ISSUE THREAD

**Issue by MagicalCube** [XT-0xFF/CustomizeAnimals#5]
System.MissingMethodException: bool Verse.Widgets.RadioButton(single,single,bool)
[Ref D9718CE]
 at CustomizeAnimals.CustomizeAnimals.CreateSettings (System.Single x, System.Single y, System.Single width, System.Single height) [0x00546] in <4d72b096e5594df4acca7b4ba74dc3fd>:0  
mod list:
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
    <version>1.5.4104 rev435</version>
    <activeMods>
        <li>zetrith.prepatcher</li>
        <li>brrainz.harmony</li>
        <li>taranchuk.fastergameloading</li>
        <li>bs.fishery</li>
        <li>ludeon.rimworld</li>
        <li>bs.performance</li>
        <li>ludeon.rimworld.royalty</li>
        <li>ludeon.rimworld.ideology</li>
        <li>ludeon.rimworld.biotech</li>
        <li>ludeon.rimworld.anomaly</li>
        <li>redmattis.betterprerequisites</li>
        <li>unlimitedhugs.hugslib</li>
        <li>oskarpotocki.vanillafactionsexpanded.core</li>
        <li>onyxae.dragonsdescent</li>
        <li>vanillaexpanded.vaeroy</li>
        <li>vanillaexpanded.vaewaste</li>
        <li>imranfish.xmlextensions</li>
        <li>vat.epoeforked</li>
        <li>sambucher.adogsaidanimalprosthetics2</li>
        <li>latta.fsharp.core</li>
        <li>latta.petknowstrueyou</li>
        <li>z4k97b.anythinginthroneroom</li>
        <li>unlimitedhugs.allowtool</li>
        <li>chad.almostthere1.5</li>
        <li>owlchemist.fridgeutilities</li>
        <li>vanillaexpanded.vpsycastse</li>
        <li>sarg.alphaanimals</li>
        <li>sarg.rimbees</li>
        <li>sarg.alphabiomes</li>
        <li>vanillaracesexpanded.android</li>
        <li>sarg.alphagenes</li>
        <li>owlchemist.toggleableoverlays</li>
        <li>lwm.deepstorage</li>
        <li>oskarpotocki.vfe.classical</li>
        <li>oskarpotocki.vfe.mechanoid</li>
        <li>sarg.alphamechs</li>
        <li>sarg.alphamemes</li>
        <li>sarg.magicalmenagerie</li>
        <li>avilmask.animalcontrols</li>
        <li>mlie.animalgenetics</li>
        <li>fluffy.animaltab</li>
        <li>oblitus.animalslogic</li>
        <li>shinzy.apparello</li>
        <li>smartkar.athenaframework</li>
        <li>mlie.betterbeggars</li>
        <li>redmattis.bettergeneinheritance</li>
        <li>voult.betterpawncontrol.fixes</li>
        <li>co.uk.epicguru.bettertranshumanists</li>
        <li>falconne.bwm</li>
        <li>vanillaexpanded.vpe.puppeteer</li>
        <li>dev.tobot.vpe.betterautocast</li>
        <li>erdelf.humanoidalienraces</li>
        <li>nals.facialanimation</li>
        <li>vanillaexpanded.vtexe.facialanims</li>
        <li>redmattis.bigsmall.core</li>
        <li>redmattis.heaven</li>
        <li>redmattis.bigsmall</li>
        <li>redmattis.lamiasandothersnakes</li>
        <li>redmattis.morexenos</li>
        <li>redmattis.scaleproject</li>
        <li>redmattis.bsslimes</li>
        <li>redmattis.undead</li>
        <li>redmattis.bigweapons</li>
        <li>redmattis.yokai</li>
        <li>vanillaexpanded.vfecore</li>
        <li>vanillaexpanded.vfemedical</li>
        <li>redmattis.bsfurniture</li>
        <li>syrus.bpansvariations</li>
        <li>calamabanana.breachableembrasures</li>
        <li>brrainz.cameraplus</li>
        <li>kopp.caravanformationimprovements</li>
        <li>fluffykittens.billcategories</li>
        <li>void.charactereditor</li>
        <li>owlchemist.cleanpathfinding</li>
        <li>mlie.climatecycleplusplus</li>
        <li>mlie.combatreadinesscheck</li>
        <li>mlie.compactworktab</li>
        <li>wiri.compositableloadouts</li>
        <li>vk.compressedraid.latest</li>
        <li>mlie.configurableroomstats</li>
        <li>russiangolden.consistentgeneinheritancebysea</li>
        <li>mlie.croprotation</li>
        <li>syrus.customizeanimals</li>
        <li>troopersmith1.deathrattle</li>
        <li>unlimitedhugs.defensivepositions</li>
        <li>merthsoft.designatorshapes</li>
        <li>mlie.differenteggsizes</li>
        <li>owlchemist.doorclearance</li>
        <li>telardo.dragselect</li>
        <li>danielwedemeyer.dressfortheweather</li>
        <li>dubwise.dubsbadhygiene</li>
        <li>dubwise.dubsbreakmod</li>
        <li>dubwise.dubsperformanceanalyzer.steam</li>
        <li>dubwise.dubsskylights</li>
        <li>mlie.ducksnolimitsideology</li>
        <li>vat.epoeforkedroyalty</li>
        <li>mlie.enterhere</li>
        <li>cozarkian.qualityframework</li>
        <li>statistno1.evolvedorgansredux</li>
        <li>karmgahl.factioncustomizer</li>
        <li>inglix.fasterbiosculptingpod</li>
        <li>kathanon.floatsubmenu</li>
        <li>hawkwood.floorsarealmostworthless</li>
        <li>mlie.gauranlentreeexpanded</li>
        <li>m00nl1ght.geologicallandforms</li>
        <li>owlchemist.giddyup</li>
        <li>mlie.giveupyourbuilding</li>
        <li>mlie.grabyourtool</li>
        <li>ancientgammoner.groundtargeter</li>
        <li>name.krypt.rimworld.rwlayout.alpha2</li>
        <li>name.krypt.rimworld.pawntablegrouped</li>
        <li>smuffle.harvestorganspostmortem</li>
        <li>orion.hospitality</li>
        <li>automatic.incidenttweaker</li>
        <li>mlie.increaseddodgechance</li>
        <li>latta.infusion</li>
        <li>smashphil.vehicleframework</li>
        <li>haecriver.injuredcarry</li>
        <li>turnovus.biotech.integratedgenes</li>
        <li>jaxe.bubbles</li>
        <li>troopersmith1.lifesupport</li>
        <li>juanlopez2008.lightsout</li>
        <li>sixdd.littlestorage2</li>
        <li>vanillaexpanded.skills</li>
        <li>cedaro.madskillsplus</li>
        <li>scorpio.makeanythingcraftable</li>
        <li>zylle.mapdesigner</li>
        <li>thereallemon.mapreroll</li>
        <li>udon.masslovein</li>
        <li>owlchemist.midsaversaver</li>
        <li>statistno1.personabond</li>
        <li>daria40k.mightypersonabondforgepatch</li>
        <li>erdelf.minifyeverything</li>
        <li>fluffy.pharmacist</li>
        <li>antaioz.modmedicinepatch</li>
        <li>kaitorisenkou.modularweapons</li>
        <li>mlie.morefactioninteraction</li>
        <li>kathanon.moregeneinfo</li>
        <li>mlie.moregraphs</li>
        <li>hobtook.mortaraccuracy</li>
        <li>mlie.multibedroyaltypatch</li>
        <li>rince.shroomsisok</li>
        <li>oblitus.mylittleplanet</li>
        <li>amch.needbaroverflow</li>
        <li>squirtingelephant.sleepdisturbed</li>
        <li>mlie.noversionwarning</li>
        <li>squirtingelephant.nozzz</li>
        <li>avilmask.nonunopinata</li>
        <li>ogre.ogrestack</li>
        <li>ronin.oldsimplestorage</li>
        <li>maeyanie.onebedtosleepwithall</li>
        <li>scorpio.optimizationleathers</li>
        <li>seohyeon.optimizationmeats</li>
        <li>turnovus.submod.backpacksarenotbelts</li>
        <li>fed1splay.pawntargetfix</li>
        <li>taranchuk.performanceoptimizer</li>
        <li>densevoid.hui.personalworkcat</li>
        <li>mehni.pickupandhaul</li>
        <li>scherub.planningextended</li>
        <li>meltup.polyamorybeds.vanilla</li>
        <li>polyamorybeds.vanilla.patch</li>
        <li>tk421storm.prioritytreatmentressurected</li>
        <li>mlie.prostheticnomissingbodyparts</li>
        <li>mute.vpesensitivity</li>
        <li>neronix17.psysight</li>
        <li>ilyvion.qualitybionics</li>
        <li>cozarkian.qualityexpanded</li>
        <li>hatti.qualitybuilder</li>
        <li>reiquard.questexpirationcriticalalert</li>
        <li>malteschulze.rimmsqol</li>
        <li>uuugggg.replacestuff</li>
        <li>oskarpotocki.vfe.empire</li>
        <li>oskarpotocki.vfe.deserters</li>
        <li>zal.spaceports</li>
        <li>vanillaexpanded.vfea</li>
        <li>co.uk.epicguru.factionloadout</li>
        <li>roolo.runandgun</li>
        <li>sf.grim.reality</li>
        <li>marximus.sameroomlovin</li>
        <li>hopeseekr.betterrimworlds.savegameshrinker</li>
        <li>owlchemist.scatteredflames</li>
        <li>evyatar108.seedspleaseliteredux</li>
        <li>avilmask.selfdyeing</li>
        <li>captainmuscles.semirandomresearch.unofficial</li>
        <li>dninemfive.settlementdescription</li>
        <li>victor.buymore</li>
        <li>stm.shellabackgrounds</li>
        <li>petetimessix.simplesidearms</li>
        <li>mlie.simplymorebridges</li>
        <li>mlie.singleplanttexturepatch</li>
        <li>denev.smartturretcovering</li>
        <li>mlie.smarterdeconstructionandmining</li>
        <li>weilbyte.snapout</li>
        <li>jpt.speakup</li>
        <li>guy762.starwarsxenotypes</li>
        <li>guy762.mm.kotorcore</li>
        <li>guy762.kotorweapons</li>
        <li>lee.theforce.psycast</li>
        <li>balistafreak.stopdropandroll</li>
        <li>mlie.stufflist</li>
        <li>stylerevised.animalist</li>
        <li>mlie.suprememelee</li>
        <li>antaioz.tdiner</li>
        <li>void.terraformrimworld</li>
        <li>sarg.jorisexperience</li>
        <li>owlchemist.toggleablereadouts</li>
        <li>vanillaexpanded.vwel</li>
        <li>oskarpotocki.vfe.pirates</li>
        <li>vanillaexpanded.vfespacer</li>
        <li>vanillaexpanded.vcooke</li>
        <li>vanillaexpanded.vcef</li>
        <li>vanillaexpanded.vcefaddon</li>
        <li>vanillaexpanded.vmemese</li>
        <li>vanillaracesexpanded.archon</li>
        <li>vanillaracesexpanded.fungoid</li>
        <li>vanillaracesexpanded.highmate</li>
        <li>vanillaracesexpanded.lycanthrope</li>
        <li>vanillaracesexpanded.phytokin</li>
        <li>vanillaracesexpanded.pigskin</li>
        <li>vanillaracesexpanded.sanguophage</li>
        <li>vanillaracesexpanded.saurid</li>
        <li>vanillaracesexpanded.waster</li>
        <li>vanillaexpanded.vanillatraitsexpanded</li>
        <li>oskarpotocki.vanillavehiclesexpanded</li>
        <li>wara.toomanymods</li>
        <li>na.toxicresistantpowerarmour</li>
        <li>marvinkosh.ughyougotme</li>
        <li>teacher.uap</li>
        <li>grimm.unlimited</li>
        <li>mrhydralisk.undergroundvault</li>
        <li>farxmai2.computersnotjunk</li>
        <li>mlie.yayoscombat3</li>
        <li>syrus.yayoscombataddon</li>
        <li>farxmai2.vaulttechnology</li>
        <li>dismarzero.vgp.vgpvegetablegarden</li>
        <li>dismarzero.vgp.vgpgardencanning</li>
        <li>dismarzero.vgp.vgpgardendrinks</li>
        <li>dismarzero.vgp.vgpgardengourmet</li>
        <li>dismarzero.vgp.vgpgardenmedicine</li>
        <li>dismarzero.vgp.vgpgardentools</li>
        <li>dismarzero.vgp.vgpmoreveggies</li>
        <li>dismarzero.vgp.vgpthreesistersplants</li>
        <li>vanillaexpanded.vpe.hemosage</li>
        <li>danzen.vpe.biotechintegration</li>
        <li>eclair155.vpebiotechpatches</li>
        <li>vanillaexpanded.vappe</li>
        <li>vanillaexpanded.vaeaccessories</li>
        <li>vanillaexpanded.varme</li>
        <li>vanillaexpanded.vanillabackstoriesexpanded</li>
        <li>vanillaexpanded.basegenerationexpanded</li>
        <li>vanillaexpanded.vbrewe</li>
        <li>vanillaexpanded.vbrewecandt</li>
        <li>vanillaexpanded.vcookestews</li>
        <li>vanillaexpanded.vcookesushi</li>
        <li>vanillaexpanded.vee</li>
        <li>oskarpotocki.vanillafactionsexpanded.settlersmodule</li>
        <li>oskarpotocki.vfe.tribals</li>
        <li>vanillaexpanded.vfearchitect</li>
        <li>vanillaexpanded.vfeart</li>
        <li>vanillaexpanded.vfefarming</li>
        <li>vanillaexpanded.vfepower</li>
        <li>vanillaexpanded.vfeproduction</li>
        <li>vanillaexpanded.vfesecurity</li>
        <li>redmattis.vanillagenesrebalanced</li>
        <li>vanillaexpanded.vgeneticse</li>
        <li>vanillaexpanded.vhe</li>
        <li>vanillaexpanded.ideo.dryads</li>
        <li>vanillaexpanded.ideo.relicsandartifacts</li>
        <li>vanillaexpanded.ideo.sophianstyle</li>
        <li>vanillaexpanded.vnutriente</li>
        <li>vanillaexpanded.outposts</li>
        <li>mlie.vanillaoutpostsexpandedexpandedranch</li>
        <li>vanillaexpanded.vpersonaweaponse</li>
        <li>vanillaexpanded.vplantse</li>
        <li>vanillaexpanded.vplantsemore</li>
        <li>vanillaexpanded.vplantsemushrooms</li>
        <li>vanillaracesexpanded.customicons</li>
        <li>vanillaracesexpanded.insector</li>
        <li>vanillaexpanded.recycling</li>
        <li>vanillaexpanded.vanillasocialinteractionsexpanded</li>
        <li>vse.perrypersistent</li>
        <li>vanillaexpanded.vanillatradingexpanded</li>
        <li>oskarpotocki.vanillavehiclesexpandedtier3</li>
        <li>vanillaexpanded.vwe</li>
        <li>vanillaexpanded.vwec</li>
        <li>vanillaexpanded.vwehw</li>
        <li>vanillaexpanded.vweft</li>
        <li>vanillaexpanded.vweg</li>
        <li>vanillaexpanded.vwenl</li>
        <li>visibleraidpoints.1trickpwnyta</li>
        <li>bodlosh.weaponstats</li>
        <li>co.uk.epicguru.whatsthatmod</li>
        <li>codeoptimist.jobsofopportunity</li>
        <li>redmattis.betterconversion</li>
        <li>funkyshit.mods.worldedit</li>
        <li>mlie.yayosnature</li>
        <li>nightkosh.zerocostimplants</li>
        <li>frozensnowfox.frozensnowfoxtweaks</li>
        <li>grizzlemethis.tradingspot.rw</li>
        <li>harkon.veaddon.vanillaexpandedextraembrasures</li>
        <li>derekbickley.ltocolonygroupsfinal</li>
        <li>og.automaticpowerswitch</li>
        <li>mlie.syrharvestyield</li>
        <li>hawkeye32.hawks.anims</li>
        <li>krkr.rocketman</li>
    </activeMods>
    <knownExpansions>
        <li>ludeon.rimworld</li>
        <li>ludeon.rimworld.royalty</li>
        <li>ludeon.rimworld.ideology</li>
        <li>ludeon.rimworld.biotech</li>
        <li>ludeon.rimworld.anomaly</li>
    </knownExpansions>
</ModsConfigData>

**Comment by ChrisF-127** [comment]
It works for me on the current version and there have not been any changes to any code relating to "RadioButton"s in 3 years. The only place they are used in this mod is for Trainability.

From what you posted I cannot tell which version of Customize Animals you are using (in case Steam did not update it properly), nor gather any more information about the error besides it saying that a base-RimWorld method is not found. 
As far as I see, you are using a slightly older version of RimWorld though: "1.5.4104" - current is: "1.5.8909". Should not cause that issue though.

You could try unsubscribing and resubscribing to CustomizeAnimals to ensure it is on the latest version and verifying your RimWorld files.


If possible you could upload a HugsLib log, those are a lot more informative.


(Misclicked on the pinning, don't mind that.)

**Comment by MagicalCube** [comment]
re-downloaded mod from github its fixed now, might been issue with how rimpy and steam mod downloads

**Comment by ChrisF-127** [comment]
Good to hear it is working for you now, I will close the issue then.
